### test user creation
POST http://localhost:8080/register
Content-Type: application/json

{
    "email": "pedrob@gmail.com",
    "user_name": "Pedro"
    "password":"abcde123"
}

### test login
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "fran.b@gmail.com",
    "password":"abcde123"
}

### drop table
delete http://localhost:8080/users

### logout 
POST http://localhost:8080/logout
